/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UmfrageRouteImport } from './routes/umfrage'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as QuellenRouteImport } from './routes/quellen'
import { Route as PotentialRouteImport } from './routes/potential'
import { Route as OekologischRouteImport } from './routes/oekologisch'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as IndexRouteImport } from './routes/index'

const UmfrageRoute = UmfrageRouteImport.update({
  id: '/umfrage',
  path: '/umfrage',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const QuellenRoute = QuellenRouteImport.update({
  id: '/quellen',
  path: '/quellen',
  getParentRoute: () => rootRouteImport,
} as any)
const PotentialRoute = PotentialRouteImport.update({
  id: '/potential',
  path: '/potential',
  getParentRoute: () => rootRouteImport,
} as any)
const OekologischRoute = OekologischRouteImport.update({
  id: '/oekologisch',
  path: '/oekologisch',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/oekologisch': typeof OekologischRoute
  '/potential': typeof PotentialRoute
  '/quellen': typeof QuellenRoute
  '/quiz': typeof QuizRoute
  '/umfrage': typeof UmfrageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/oekologisch': typeof OekologischRoute
  '/potential': typeof PotentialRoute
  '/quellen': typeof QuellenRoute
  '/quiz': typeof QuizRoute
  '/umfrage': typeof UmfrageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/oekologisch': typeof OekologischRoute
  '/potential': typeof PotentialRoute
  '/quellen': typeof QuellenRoute
  '/quiz': typeof QuizRoute
  '/umfrage': typeof UmfrageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chatbot'
    | '/oekologisch'
    | '/potential'
    | '/quellen'
    | '/quiz'
    | '/umfrage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chatbot'
    | '/oekologisch'
    | '/potential'
    | '/quellen'
    | '/quiz'
    | '/umfrage'
  id:
    | '__root__'
    | '/'
    | '/chatbot'
    | '/oekologisch'
    | '/potential'
    | '/quellen'
    | '/quiz'
    | '/umfrage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatbotRoute: typeof ChatbotRoute
  OekologischRoute: typeof OekologischRoute
  PotentialRoute: typeof PotentialRoute
  QuellenRoute: typeof QuellenRoute
  QuizRoute: typeof QuizRoute
  UmfrageRoute: typeof UmfrageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/umfrage': {
      id: '/umfrage'
      path: '/umfrage'
      fullPath: '/umfrage'
      preLoaderRoute: typeof UmfrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quellen': {
      id: '/quellen'
      path: '/quellen'
      fullPath: '/quellen'
      preLoaderRoute: typeof QuellenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/potential': {
      id: '/potential'
      path: '/potential'
      fullPath: '/potential'
      preLoaderRoute: typeof PotentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oekologisch': {
      id: '/oekologisch'
      path: '/oekologisch'
      fullPath: '/oekologisch'
      preLoaderRoute: typeof OekologischRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatbotRoute: ChatbotRoute,
  OekologischRoute: OekologischRoute,
  PotentialRoute: PotentialRoute,
  QuellenRoute: QuellenRoute,
  QuizRoute: QuizRoute,
  UmfrageRoute: UmfrageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
